/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code27;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {


    @Test void insertionSortTest(){
        App classUnderTest = new App();
        assertEquals(Arrays.toString(classUnderTest.mergeSort(new int[]{8, 4, 23, 42, 16, 15})), Arrays.toString(new int[]{4, 8, 15, 16, 23, 42}));
    }

    @Test void insertionSortTest2(){
        App classUnderTest = new App();
        assertEquals(Arrays.toString(classUnderTest.mergeSort(new int[]{20,18,12,8,5,-2})), Arrays.toString(new int[]{-2, 5, 8, 12, 18, 20}));
    }

    @Test void insertionSortTest3(){
        App classUnderTest = new App();
        assertEquals(Arrays.toString(classUnderTest.mergeSort(new int[]{5, 12, 7, 5, 5, 7})), Arrays.toString(new int[]{5, 5, 5, 7, 7, 12}));
    }

    @Test void insertionSortTest4(){
        App classUnderTest = new App();
        assertEquals(Arrays.toString(classUnderTest.mergeSort(new int[]{5, 12, 7, 5, 5, 7})), Arrays.toString(new int[]{5, 5, 5, 7, 7, 12}));
    }

    @Test void insertionSortTest5(){
        App classUnderTest = new App();
        assertEquals(Arrays.toString(classUnderTest.mergeSort(new int[]{1, 0, -1})), Arrays.toString(new int[]{-1, 0, 1}));
    }
}
