
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


            // declare a linked list
        linkedList1<String> newlist = new linkedList1();

        // insert nodes to the head of linked list
        newlist.insertNode("A");
        newlist.insertNode("B");
        newlist.insertNode("C");
        newlist.insertNode("G");
        newlist.insertNode("M");
        newlist.insertNode("N");

        System.out.println(" nods in linked list : ");
        newlist.printList();

         newlist.KthFromLast(9);
        newlist.KthFromLast(6);
        newlist.KthFromLast(0);
        newlist.KthFromLast(-1);
       newlist.KthFromLast(4);

//        // print the nodes in linked list



    }
}

