/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code30;

import code30.HashTable;

public class App {


    public static void main(String[] args) {

        System.out.println("Welcome to Hash Tables Class");

        HashTable<String, String> HashTable = new HashTable<String,String>();
        HashTable.set("JAVA", "JAVA");
        HashTable.set("Amman", "Amman");
        HashTable.set("Jordan", "Jordan");
        HashTable.set("J", "J");
        HashTable.set("Bob", "Bob");
        HashTable.set("Carl", "Carl");
        HashTable.set("Sadan", "2015");
        HashTable.set("Elien", "2014");

        System.out.println("\nThe index of => JAVA" + " is => " + HashTable.hash("JAVA"));
        System.out.println("The index of => Amman" + " is => " + HashTable.hash("Amman"));
        System.out.println("The index of => Bob" + " is => " + HashTable.hash("Bob"));
        System.out.println("The index of => Jordan" + " is => " + HashTable.hash("Jordan"));
        System.out.println("The index of => Sadan" + " is => " + HashTable.hash("Sadan"));
        System.out.println("The index of => Elien" + " is => " + HashTable.hash("Elien"));


        System.out.println("\nHashTable contains Amman : "+ HashTable.contains("Amman"));
        System.out.println("HashTable contains Bob : "+ HashTable.contains("Bob"));
        System.out.println("HashTable contains Manar : "+ HashTable.contains("Manar"));
        System.out.println("HashTable contains 155 : "+ HashTable.contains("155"));
        System.out.println("HashTable contains 134 : "+ HashTable.contains("134"));

        System.out.println("\nKeys are : " + HashTable.keys());

        System.out.println("\nKey : JAVA ==>  value : "+ HashTable.get("JAVA"));
        System.out.println("Key : Jordan ==>  value : "+ HashTable.get("Jordan"));
        System.out.println("Key : Sadan ==>  value : "+ HashTable.get("Sadan"));
        System.out.println("Key : Elien ==>  value : "+ HashTable.get("Elien"));


    }
}
