/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code28;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void quickSortTest(){
        App classUnderTest = new App();
        int[] arr=new int[]{8, 4, 23, 42, 16, 15};
        assertEquals(Arrays.toString(classUnderTest.quickSort(arr,0,arr.length-1)), Arrays.toString(new int[]{4, 8, 15, 16, 23, 42}));
    }

    @Test void quickSortTest2(){
        App classUnderTest = new App();
        int[] arr =new int[]{20,18,12,8,5,-2};
        assertEquals(Arrays.toString(classUnderTest.quickSort(arr,0,arr.length-1)), Arrays.toString(new int[]{-2, 5, 8, 12, 18, 20}));
    }

    @Test void quickSortTest3(){
        App classUnderTest = new App();
        int arr[]=new int[]{5, 12, 7, 5, 5, 7};
        assertEquals(Arrays.toString(classUnderTest.quickSort(arr,0,arr.length-1)), Arrays.toString(new int[]{5, 5, 5, 7, 7, 12}));
    }

    @Test void quickSortTest4(){
        App classUnderTest = new App();
        int[] arr=new int[]{5, 12, 7, 5, 5, 7};
        assertEquals(Arrays.toString(classUnderTest.quickSort(arr,0,arr.length-1)), Arrays.toString(new int[]{5, 5, 5, 7, 7, 12}));
    }

    @Test void quickSortTest5(){
        App classUnderTest = new App();
        int[] arr=new int[]{1, 0, -1};
        assertEquals(Arrays.toString(classUnderTest.quickSort(arr,0,arr.length-1)), Arrays.toString(new int[]{-1, 0, 1}));
    }
}
