/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code36;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());

        Graph graph = new Graph();

        graph.addNode("Pandora");
        graph.addNode("Arendelle");
        graph.addNode("Metroville");
        graph.addNode("Monstroplolis");
        graph.addNode("Narnia");
        graph.addNode("Naboo");

        graph.addEdges("Pandora","Arendelle");
        graph.addEdges("Arendelle","Metroville");
        graph.addEdges("Arendelle","Monstroplolis");
        graph.addEdges("Metroville","Narnia");
        graph.addEdges("Metroville","Naboo");
        graph.addEdges("Metroville","Monstroplolis");
        graph.addEdges("Naboo","Narnia");
        graph.addEdges("Monstroplolis","Naboo");

        System.out.println(graph.breadthFirst("Pandora"));

    }
}
