/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code26;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static int[] insertionSort(int[] arr){
        for (int i = 1; i < arr.length; i++) {
            int j = i-1;
            int temp = arr[i];

            while (j>=0 && temp< arr[j])
            {
                arr[j+1] = arr[j];
                j = j-1;
            }
            arr[j+1] = temp;
        }
        return arr;
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());

        int[] inputArray = new int[]{8,4,23,42,16,15};
        System.out.println("\n original array ==>   " + Arrays.toString(inputArray));
        System.out.println("after insertion sort  " +Arrays.toString(insertionSort(inputArray))+"\n");

        int[] reverseSorted = new int[]{20,18,12,8,5,-2};
        System.out.println(" original array ==>   " + Arrays.toString(reverseSorted));
        System.out.println("after insertion sort  " +Arrays.toString(insertionSort(reverseSorted))+"\n");

        int[] fewUniques = new int[]{5,12,7,5,5,7};
        System.out.println(" original array ==>   " + Arrays.toString(fewUniques));
        System.out.println("after insertion sort  " +Arrays.toString(insertionSort(fewUniques))+"\n");

        int[] nearlySorted = new int[]{5,12,7,5,5,7};
        System.out.println(" original array ==>   " + Arrays.toString(nearlySorted));
        System.out.println("after insertion sort  " +Arrays.toString(insertionSort(nearlySorted))+"\n");

    }
}
