/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code38;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


        Graph graph = new Graph();

        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");
        graph.addNode("D");
        graph.addNode("E");
        graph.addNode("F");
        graph.addNode("G");
        graph.addNode("H");

        graph.addEdges("A","B");
        graph.addEdges("A","D");
        graph.addEdges("B","D");
        graph.addEdges("D","F");
        graph.addEdges("B","C");
        graph.addEdges("C","G");
        graph.addEdges("D","E");
        graph.addEdges("D","H");
        graph.addEdges("F","H");

        System.out.println(graph.depthFirst(new Vertex ("A")));




    }
}
