/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code37;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
//    @Test void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
    @Test
    void test1()
    {
        Graph graph = new Graph();
        graph.addNode("Pandora");
        graph.addNode("Arendelle");
        graph.addNode("Metroville");
        graph.addNode("Monstroplolis");
        graph.addNode("Narnia");
        graph.addNode("Naboo");

        graph.addEdges("Metroville", "Pandora", 82);
        graph.addEdges("Metroville", "Narnia", 37);

        String[] arr = {"Pandora","Metroville","Narnia"};
        assertEquals(graph.businessTrip(graph, arr),119);
    }
    @Test
    void test2()
    {
        Graph graph = new Graph();
        graph.addNode("Pandora");
        graph.addNode("Arendelle");
        graph.addNode("Metroville");
        graph.addNode("Monstroplolis");
        graph.addNode("Narnia");
        graph.addNode("Naboo");

        graph.addEdges("Metroville", "Pandora", 82);
        graph.addEdges("Metroville", "Narnia", 37);

        String[] arr = {"Arendelle","Naboo","Narnia"};
        assertEquals(graph.businessTrip(graph, arr),0);
    }
    @Test
    void test3()
    {
        Graph graph = new Graph();
        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");
        graph.addNode("D");

        graph.addEdges("A", "B", 5);
        graph.addEdges("C", "D", 10);
        graph.addEdges("A", "D", 12);

        String[] arr = {"A","D"};
        assertEquals(graph.businessTrip(graph, arr),12);
    }
    @Test
    void test4()
    {
        Graph graph = new Graph();
        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");
        graph.addNode("D");

        graph.addEdges("A", "B", 5);
        graph.addEdges("C", "D", 10);
        graph.addEdges("A", "D", 12);

        String[] arr = {"C","D","A","B"};
        assertEquals(graph.businessTrip(graph, arr),27);
    }
    @Test
    void test5()
    {
        Graph graph = new Graph();
        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");
        graph.addNode("D");

        graph.addEdges("A", "B", 17);
        graph.addEdges("C", "D", 10);
        graph.addEdges("A", "D", 12);
        graph.addEdges("B", "D", 20);
        graph.addEdges("B", "C", 4);

        String[] arr = {"A","C"};
        assertEquals(graph.businessTrip(graph, arr),0);
    }
}
