/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());

        System.out.println("//////////// here is binary tree /////////////");
        BinaryTree <Integer> biTree = new BinaryTree<>();

        biTree.setRoot(new Node<>(15));

        biTree.getRoot().setLeft(new Node<>(30));
        biTree.getRoot().setRight( new Node<>(25));

        biTree.getRoot().getLeft().setLeft(new Node<>(35));
        biTree.getRoot().getLeft().setRight(new Node<>(40));
        biTree.getRoot().getRight().setLeft(new Node<>(45));
        biTree.getRoot().getRight().setRight(new Node<>(50));

        System.out.println(biTree);
        System.out.println("\n pre order ==>  "+biTree.preOrder(biTree.getRoot()));
        System.out.println("\n in order ==>  "+biTree.inOrder(biTree.getRoot()));
        System.out.println("\n post order ==>  "+biTree.postOrder(biTree.getRoot()));

        System.out.println("\n//////////// here is binary search tree /////////////\n");
        BinarySearchTree<Integer> binSearchT = new BinarySearchTree();
        binSearchT.add(50);
        binSearchT.add(30);
        binSearchT.add(40);
        binSearchT.add(20);
        binSearchT.add(60);
        System.out.println(binSearchT);

        System.out.println("\nis tree contains 40 ? "+ binSearchT.contains(40));
        System.out.println("is tree contains 50 ? "+ binSearchT.contains(50));
        System.out.println("is tree contains 20 ? "+ binSearchT.contains(20));
        System.out.println("is tree contains 10 ? "+ binSearchT.contains(10));
        System.out.println("is tree contains 4  ? "+ binSearchT.contains(4));
        System.out.println("is tree contains 85 ? "+ binSearchT.contains(85));
        }

    }

