/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leftjoin;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("\n");
        LeftJoin leftJoinObj = new LeftJoin();
        HashTable<String, String> HashTable = new HashTable<String,String>();
        HashTable.set("diligent", "employed");
        HashTable.set("fond", "enamored");
        HashTable.set("guide", "usher");
        HashTable.set("outfit", "garb");
        HashTable.set("wrath", "anger");

        HashTable<String, String> HashTable2 = new HashTable<String,String>();
        HashTable2.set("diligent", "idle");
        HashTable2.set("fond", "averse");
        HashTable2.set("guide", "follow");
        HashTable2.set("flow", "jam");
        HashTable2.set("wrath", "delight");

        System.out.println(leftJoinObj.leftJoin(HashTable,HashTable2));
    }
}
