/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code37;

import java.util.ArrayList;
import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        Graph graph = new Graph();
        graph.addNode("Pandora");
        graph.addNode("Arendelle");
        graph.addNode("Metroville");
        graph.addNode("Monstroplolis");
        graph.addNode("Narnia");
        graph.addNode("Naboo");

        graph.addEdges("Pandora", "Arendelle", 150);
//        graph.addEdges("Pandora", "Narnia", 300);
        graph.addEdges("Metroville", "Pandora", 82);
        graph.addEdges("Arendelle", "Metroville", 99);
        graph.addEdges("Arendelle", "Monstroplolis", 42);
        graph.addEdges("Metroville", "Monstroplolis", 105);
        graph.addEdges("Monstroplolis", "Naboo", 73);
        graph.addEdges("Metroville", "Naboo", 26);
        graph.addEdges("Metroville", "Narnia", 37);
        graph.addEdges("Narnia", "Naboo", 250);

        String[] arr = {"Metroville","Pandora"};
        String[] arr1 = {"Arendelle","Monstroplolis","Naboo"};
        String[] arr2 = {"Naboo","Pandora"};
        String[] arr3 = {"Narnia","Arendelle","Naboo"};



        int X =graph.businessTrip(graph, arr);
        System.out.println(Arrays.toString(arr) + " ==>   "+ (X > 0 ? "True, $" + X : "False, $" + X)+"\n");

        int X1 =graph.businessTrip(graph, arr1);
        System.out.println(Arrays.toString(arr1) + " ==>   "+ (X1 > 0 ? "True, $" + X1 : "False, $" + X1)+"\n");

        int X2 =graph.businessTrip(graph, arr2);
        System.out.println(Arrays.toString(arr2) + " ==>   "+ (X2 > 0 ? "True, $" + X2 : "False, $" + X2)+"\n");

        int X3 =graph.businessTrip(graph, arr3);
        System.out.println(Arrays.toString(arr3) + "  ==>   "+ (X3 > 0 ? "True, $" + X3 : "False, $" + X3)+"\n");


    }
}