
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

//import java.util.LinkedList;


class AppTest {

    // zip 2 lists with the same size
    @Test void zipListTest()
    {linkedList1<Integer> newlist = new linkedList1();
        linkedList1<Integer> list1 = new linkedList1();
        linkedList1<Integer> list2 = new linkedList1();
        list1.append(1);
        list1.append(3);

        list2.append(2);
        list2.append(4);
        assertEquals((newlist.zipList(list1,list2)).toString(),"\"{1}->{2}->{3}->{4}->NULL\"" );
    }
    // zip test if size of list 1 grater than size of list 2
    @Test void zipListTest2()
    {
        linkedList1<Integer> newlist = new linkedList1();
        linkedList1<Integer> list1 = new linkedList1();
        linkedList1<Integer> list2 = new linkedList1();
        list1.append(1);
        list1.append(3);
        list1.append(5);
        list2.append(2);
        list2.append(4);
        assertEquals((newlist.zipList(list1,list2)).toString(),"\"{1}->{2}->{3}->{4}->{5}->NULL\"");
    }

    // zip test if size of list 2 grater than size of list 1
    @Test void zipListTest3()
    {
        linkedList1<Integer> newlist = new linkedList1();
        linkedList1<Integer> list1 = new linkedList1();
        linkedList1<Integer> list2 = new linkedList1();
        list1.append(1);
        list1.append(3);

        list2.append(2);
        list2.append(4);
        list1.append(6);
        assertEquals((newlist.zipList(list1,list2)).toString(),"\"{1}->{2}->{3}->{4}->{6}->NULL\"");
    }

   



}