/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code35;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Graph graph = new Graph();
    // add nodes to graph
        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");

        // add edge between A and B without weight
        graph.addEdges("A","B");

        // add edge between B and C with weight 30
        graph.addEdges("B","C",30);
        // add edge between B and C with weight 20
        graph.addEdges("C","A",20);

        System.out.println("all nodes  ==>  "+graph.getNodes()+"\n");

        System.out.println("neighbours of A ==>  "+graph.getNeighbors("A"));
        System.out.println("neighbours of B ==>  "+graph.getNeighbors("B"));
        System.out.println("neighbours of C ==>  "+graph.getNeighbors("C")+"\n");

        System.out.println("size = "+ graph.size()+"\n");

    }
}
