/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code36;

import org.junit.jupiter.api.Test;

import java.util.HashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
//    @Test void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }

    @Test void test1(){
        Graph graph = new Graph();
        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");
        graph.addNode("D");

        graph.addEdges("A","B");
        graph.addEdges("A","C");
        graph.addEdges("B","C");
        graph.addEdges("B","D");


        Set<String> bfs = graph.breadthFirst("A");
        Set<String> arr = new HashSet<>();
        arr.add("A");
        arr.add("B");
        arr.add("C");
        arr.add("D");

        assertEquals(arr,bfs);
    }

    @Test void test2(){
        Graph graph = new Graph();
        graph.addNode("1");
        graph.addNode("10");
        graph.addNode("25");
        graph.addNode("2");
        graph.addNode("13");

        graph.addEdges("10","2");
        graph.addEdges("25","1");
        graph.addEdges("10","25");
        graph.addEdges("10","1");
        graph.addEdges("25","2");
        graph.addEdges("2","1");
        graph.addEdges("13","1");


        Set<String> bfs = graph.breadthFirst("1");
        Set<String> arr = new HashSet<>();
        arr.add("1");
        arr.add("25");
        arr.add("10");
        arr.add("2");
        arr.add("13");

        assertEquals(arr,bfs);
    }

    @Test void test3() {
        Graph graph = new Graph();
        graph.addNode("Pandora");
        graph.addNode("Arendelle");
        graph.addNode("Monstroplolis");
        graph.addNode("Narnia");

        graph.addEdges("Pandora", "Arendelle");
        graph.addEdges("Arendelle", "Monstroplolis");
        graph.addEdges("Narnia", "Monstroplolis");

        Set<String> bfs = graph.breadthFirst("Pandora");
        Set<String> arr = new HashSet<>();
        arr.add("Pandora");
        arr.add("Arendelle");
        arr.add("Monstroplolis");
        arr.add("Narnia");
        assertEquals(arr,bfs);
    }
}
